apiVersion: apps/v1
kind: Deployment
metadata:
  name: regrequest
  labels:
    app: regrequest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: regrequest
  template:
    metadata:
      labels:
        app: regrequest
    spec:
      containers:
        - name: regrequest
          image: username/regrequest:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5